---
title: "Welfare Report"
author: "김민준7"
date: '2020 12 4 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. 데이터 준비
  + https://www.koweps.re.kr:442

#### 1-1. 패키지 준비
```{r}
#install.packages("foreign")
#install.packages("dplyr")
#install.packages("ggplot2")
#install.packages("readxl")

library(foreign)
library(dplyr)
library(ggplot2)
library(readxl)
```

#### 1-2. 데이터 불러오기
```{r}
raw_welfare <- read.spss(file="../data/Koweps_hpc10_2015_beta1.sav", to.data.frame = T)
# head(raw_welfare)

# 복사본
welfare <- raw_welfare
```

#### 1-3. 데이터 검토
```{r}
dim(welfare)
str(welfare)
View(welfare)
```

#### 1-4. 특성 선택
```{r}
welfare <- rename(welfare, sex=h10_g3, birth=h10_g4, marriage=h10_g10,
                  religion=h10_g11, income=p1002_8aq1, code_job=h10_eco9,
                  code_region=h10_reg7)

welfare <- welfare[, c("sex", "birth", "marriage", "religion", "income",
                       "code_job", "code_region")]

str(welfare)
```

# 2. 탐색적 데이터 분석

### 2-1. 성별에 따른 월급의 차이?

```{r}
# 성별 변수 검토
class(welfare$sex)
table(welfare$sex)
```

```{r}
# 월급 변수 검토
class(welfare$income)
summary(welfare$income)

qplot(welfare$income)
qplot(welfare$income) + xlim(0, 1000)
```



#### 2-1-1. 변수 전처리

```{r}
# 성별 항목에 대한 이름 변경
welfare$sex <- ifelse(welfare$sex == 1, "male", "female")
table(welfare$sex)
qplot(welfare$sex)
```

```{r}
# 성별변수에 대한 전처리 : 이상치, 결측치
table(welfare$sex)

# 만약 성별에 이상치가 있었다면
welfare$sex <- ifelse(welfare$sex == 9, NA, welfare$sex)
table(is.na(welfare$sex))
```

```{r}
# 월급변수에 대한 전처리 : 이상치, 결측치
welfare$income <- ifelse(welfare$income %in% c(0, 9999), NA, welfare$income)
table(is.na(welfare$income))
```

#### 2-1-2. 결론

```{r}
# 성별에 따른 급여 평균 구하기
sex_income <- welfare %>% filter(!is.na(income)) %>% group_by(sex) %>%
  summarise(mean_income=mean(income))

sex_income
```

```{r}
ggplot(data=sex_income, aes(x=sex, y=mean_income)) + geom_col()
```

### 2-2. 나이와 월급의 관계 : 몇살에 월급을 가장 많이 받을까?

```{r}
# 나이 변수에 대한 검토
class(welfare$birth)
summary(welfare$birth)
```

```{r}
qplot(welfare$birth)
```

#### 2-2-1. 변수 전처리

```{r}
### 나이 변수에 대한 전처리 : 이상치, 결측치, 파생변수

# 이상치 확인
summary(welfare$birth)

# 결측치 확인
table(is.na(welfare$birth))

# 나이 파생변수 생성 : age
welfare$age <- 2015 - welfare$birth + 1
summary(welfare$age)
```

```{r}
qplot(welfare$age)
```

#### 2-2-2. 결과

```{r}
# 나이별로 급여 평균 구하기
age_income <- welfare %>% filter(!is.na(income)) %>% group_by(age) %>%
  summarise(mean_income=mean(income))

head(age_income)
```

```{r}
ggplot(age_income, aes(age, mean_income)) + geom_line()
```

### 2-3. 연령대에 따른 월급의 차이?

#### 2-3-1. 변수 전처리 : 파생변수 생성

  + 초년(young) : 30세 미만
  + 중년(middle) : 30 ~ 59세
  + 노년(old) : 60세 이상

```{r}
welfare <- welfare %>% 
  mutate(ageg = ifelse(age<30, "young", ifelse(age<=59, "middle", "old")))

table(welfare$ageg)
```

```{r}
qplot(welfare$ageg)
```

#### 2-3-2. 결론

```{r}
# 연령대별로 평균 급여
ageg_income <- welfare %>% filter(!is.na(income)) %>% group_by(ageg) %>%
  summarise(mean_income=mean(income))

ageg_income
```

```{r}
ggplot(ageg_income, aes(ageg, mean_income)) + geom_col()

# 막대의 순서 바꾸기
ggplot(ageg_income, aes(ageg, mean_income)) + geom_col() +
  scale_x_discrete(limits=c("young", "middle", "old"))
```

### 2-4. 연령대및 성별 따른 월급의 차이?

#### 2-4-1. 연령대 및 성별 월급 차이

```{r}
ageg_sex_income <- welfare %>% filter(!is.na(income)) %>% 
  group_by(ageg, sex) %>% summarise(mean_income=mean(income))

ageg_sex_income
```

```{r}
ggplot(ageg_sex_income, aes(x=ageg, y=mean_income, fill=sex)) + 
  geom_col(position = "dodge") + 
  scale_x_discrete(limits=c("young", "middle", "old"))
```

#### 2-4-2. 나이 및 성별 월급 차이

```{r}
age_sex_income <- welfare %>% filter(!is.na(income)) %>% 
  group_by(age, sex) %>% summarise(mean_income=mean(income))

head(age_sex_income)
```

```{r}
ggplot(age_sex_income, aes(x=age, y=mean_income, col=sex)) + geom_line()
```

### 2-5. 직업별 월급 차이?

```{r}
# 직업 변수 검토
class(welfare$code_job)
table(welfare$code_job)
```

#### 2-5-1. 변수 전처리

```{r}
# 직종 코드 변수값을 직종명으로 변경

list_job = read_excel("../data/Koweps_Codebook.xlsx", col_names = T, 
                      sheet = 2)

head(list_job)
dim(list_job)

welfare <- left_join(welfare, list_job, id="code_job")
head(welfare)

welfare %>% filter(!is.na(code_job)) %>% select(code_job, job) %>% head(10)
```

#### 2-5-2. 결론

```{r}
# 직업별 평균 급여 구하기
job_income <- welfare %>% filter(!is.na(job) & !is.na(income)) %>%
  group_by(job) %>% summarise(mean_income = mean(income))

head(job_income)

top10 <- job_income %>% arrange(desc(mean_income)) %>% head(10)
top10
```

```{r}
bottom10 <- job_income %>% arrange(mean_income) %>% head(10)
bottom10
```

```{r}
ggplot(top10, aes(reorder(job, mean_income), mean_income)) + geom_col() + coord_flip()
```

```{r}
ggplot(bottom10, aes(reorder(job, mean_income), mean_income)) + geom_col() + coord_flip() + ylim(0, 850)
```

### 2-6. 성별 직업 빈도 : 성별로 어떤 직업이 가장 많을까?
```{r}
job_male<-welfare %>% filter(!is.na(job) & sex == "male") %>% group_by(job) %>% summarise(count=n()) %>% arrange(desc(count)) %>% head(10)

job_male

ggplot(job_male, aes(reorder(job,count),count)) + geom_col()+coord_flip()
```
```{r}
job_female<-welfare %>% filter(!is.na(job) & sex == "female") %>% group_by(job) %>% summarise(count=n()) %>% arrange(desc(count)) %>% head(10)

job_female

ggplot(job_female, aes(reorder(job,count),count)) + geom_col()+coord_flip()
```



### 2-7. 종교 유무에 따른 이혼율
```{r}
# 종교 변수 검토
class(welfare$religion)
table(welfare$religion)
```
```{r}
# 혼인 변수 검토
class(welfare$marriage)
table(welfare$marriage)
```

# 2-7-1. 종교 변수 전처리
```{r}
# 종교 유무에 따라 1은 yes, 2는 no로 변경
welfare$religion <- ifelse(welfare$religion == 1 , 'yes', 'no')
table(welfare$religion)

qplot(welfare$religion)
```


### 2-8. 연령대 및 종교 유무에 따른 이혼율

```{r}
# 이혼 여부에 따라 파생변수 추가
# group_marriage : 1은 marriage, 3은 divorce, 나머지는 NA로 처리)
welfare$group_marriage <- ifelse(welfare$marriage==1, 'marriage', ifelse(welfare$marriage==3, 'divorce', NA))
table(welfare$group_marriage)
```
### 2-7-3. 결론
```{r}
# 종교 유무에 따른 이혼율표를 작성
religion_marriage<- welfare %>% filter(!is.na(group_marriage)) %>% group_by(religion, group_marriage) %>% summarise(n=n()) %>% mutate(tot_group = sum(n)) %>% mutate(pct = round(n/tot_group*100,1))

religion_marriage
```

```{r}
# 이혼율표 작성
divorce <- religion_marriage %>% filter(group_marriage == 'divorce') %>% select(religion, pct)

divorce
```
```{r}
# 그래프 만들기
ggplot(divorce, aes(religion, pct))+geom_col()
```


```{r}
# 연령대별로 이혼율표를 작성
ageg_marriage <- welfare %>% filter(!is.na(group_marriage)) %>% group_by(ageg, group_marriage) %>% summarise(n=n()) %>% mutate(tot_group=sum(n)) %>% mutate(pct=round(n/tot_group*100,1))

ageg_marriage
```

```{r}
# 종교 유무에 따라 이혼율의 차이가 연령대별로 다른지 확인
ageg_religion_marriage <- welfare %>% filter(!is.na(group_marriage) & ageg !='young') %>% group_by(ageg, religion, group_marriage) %>% summarise(n=n()) %>% mutate(tot_group =sum(n)) %>% mutate(pct=round(n/tot_group*100,1))

ageg_religion_marriage
```

```{r}
df_divorce <- ageg_religion_marriage %>% filter(group_marriage == 'divorce') %>% select(ageg, religion, pct)

df_divorce
```

```{r}
ggplot(df_divorce, aes(ageg, pct,fill=religion)) + geom_col(position = 'dodge')
```

### 2-9. 지역별 연령대 비율
```{r}
# 지역 변수 검토
table(welfare$code_region)
```
#### 2-9-1. 지역 변수 전처리
```{r}
list_region <- data.frame(code_region=c(1:7),
                         region = c("서울","수도권(인천/경기)", "부산/경남/울산","대구/경북","대전/충남", "강원/충북", "광주/전남/전북/제주도"))
list_region
```

```{r}
welfare <-left_join(welfare, list_region, id="code_region")

welfare %>% select(code_region,region) %>% head(10)

```


#### 2-9-2. 결론
```{r}
# 지역별 연령대 비율표 작성
region_ageg<- welfare %>% group_by(region, ageg) %>% summarise(n=n()) %>% mutate(tot_group = sum(n)) %>% mutate(pct = round(n/tot_group*100,1))
region_ageg
```
```{r}
ggplot(region_ageg, aes(region, pct, fill=ageg)) +geom_col()+coord_flip()
```
```{r}
# 노년층 비율이 높은 순으로 막대를 정렬
list_order_old <- region_ageg %>% filter(ageg=='old') %>% arrange(pct)

list_order_old
```
```{r}
# 노년층에 대한 지역명 변수
order <- list_order_old$region

order


```
```{r}
ggplot(region_ageg, aes(region, pct, fill=ageg)) +geom_col()+coord_flip() +scale_x_discrete(limits=order)
```





































